# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy:
    runs-on: ubuntu-latest   
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          key: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /home/${{ secrets.VPS_SSH_USERNAME }}/course-work-cd-traefik/
            wget https://raw.githubusercontent.com/ikuyotagan/course-work-cd-traefik/main/docker-compose.yml
            echo "Pull new image"
            docker-compose -f /home/${{ secrets.VPS_SSH_USERNAME }}/course-work-cd-traefik/docker-compose.yml pull
            echo "Restart the container"
            docker-compose -f /home/${{ secrets.VPS_SSH_USERNAME }}/course-work-cd-traefik/docker-compose.yml up --force-recreate --build --no-deps -d
            echo "Delete old image"
            docker image prune -f
